name: 'Install OpenCilk Compiler'
author: 'Alejandro Armas'
inputs: 

runs:
  using: 'composite'
  steps:

    - name: Cache OpenCilk
      id: opencilk-cache
      uses: actions/cache@v3
      env: 
        cache-name: opencilk-installation-script
      with:
        path: opencilk-install.sh
        key: ${{ runner.os }}-${{runner.arch}}-${{env.cache-name}}

    - if: ${{ steps.opencilk-cache.outputs.cache-hit != 'true'}}
      name: Download OpenCilk Install Script
      run: chmod +x ./download-opencilk.sh      
    - if: ${{ steps.opencilk-cache.outputs.cache-hit != 'true'}}
      run: ./download-opencilk.sh v2.0 x86_64 opencilk-install.sh
      shell: bash
    - name: Install OpenCilk Compiler
      run: ./setup-opencilk.sh
      shell: bash
    - name: Validate Installation
      run: /opt/opencilk/bin/clang++ --version
      shell: bash