name: 'Install OpenCilk Compiler'
author: 'Alejandro Armas'

runs:
  using: 'composite'
  steps:
    - name: Cache OpenCilk
      id: opencilk-cache
      uses: actions/cache@v3
      env: 
        cache-name: opencilk-installation-script
      with:
        path: ./${{ env.install-script-name}}
        key: ${{ runner.os }}-${{ runner.arch}}-${{env.cache-name}}

    - if: ${{ steps.opencilk-cache.outputs.cache-hit != 'true'}}
      name: Download OpenCilk Install Script
      run: chmod +x ./download-opencilk.sh  
      shell: bash    
    - if: ${{ steps.opencilk-cache.outputs.cache-hit != 'true'}}
      run: ./download-opencilk.sh v2.0 x86_64 ${{env.install-script-name}}
      shell: bash
    - name: Install OpenCilk Compiler
      run: ./setup-opencilk.sh ${{env.install-script-name}}
      shell: bash
    - name: Validate Installation
      run: /opt/opencilk/bin/clang++ --version
      shell: bash