name: 'Install OpenCilk Compiler'
author: 'Alejandro Armas'

runs:
  using: 'composite'
  steps:
    - run: ./setup-opencilk.sh
      shell: bash
    - run: /opt/opencilk/bin/clang++ --version
      shell: bash