name: 'Install OpenCilk Compiler'

on: [push]

jobs:
  OpenCilkInstall:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: 'Installation Script'
        uses: ./
